### ISSUE TITLE
Cerita 2 hilang

### ISSUE THREAD

**Issue by mhdfadlyhasan** [2018-PemrogramanWeb-D/tugas7-fp-maca#1]
![image](https://user-images.githubusercontent.com/37266671/50051045-fadd8d80-013c-11e9-89c6-948668ae0976.png)

**Comment by 17-193VaniaC** [comment]
terima kasih fadly, website maca sudah tidak lagi menggunakan file php untuk setiap halaman ceritanya dan sudah direvisi . Untuk versi terbarunya ada di folder versi_revisi

**Comment by 17-193VaniaC** [comment]
terima kasih fadly, website maca sudah tidak lagi menggunakan file php untuk setiap halaman ceritanya dan sudah direvisi . Untuk versi terbarunya bisa dilihat di folder versi_revisi.

**Comment by ridho13** [comment]
utk revisi tolong jgn membuat folder baru, tp commit-an yg lama ditumpuk dgn commit-an yg baru.. trims

**Comment by ridho13** [comment]
utk memfix bug tlg sertakan referensi ke commit-an dmn terdapat fix bugnya.
contoh bs dilihat di https://github.com/2018-PemrogramanWeb-D/tugas7-fp-ngr/issues/3

mhdfadlyhasan closed this in 9aef5ad 5 hours ago
