### ISSUE TITLE
tidak ada laman index

### ISSUE THREAD

**Issue by n0tlu5** [2018-PemrogramanWeb-D/tugas7-fp-maca#2]
![image](https://user-images.githubusercontent.com/20925605/50071476-6f2f3400-0204-11e9-870c-fd60a0e8b5bf.png)

**Comment by 17-193VaniaC** [comment]
Website sudah direvisi dan versi terbarunya ada di folder versi_revisi. Setiap user yang belum login akan diarahakan ke login.php.
